
package test;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://server.jaxws.test.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://server.jaxws.test.com/", className = "test.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://server.jaxws.test.com/", className = "test.AddResponse")
    @Action(input = "http://server.jaxws.test.com/Calculator/addRequest", output = "http://server.jaxws.test.com/Calculator/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @return
     *     returns java.util.List<test.PersonBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonList", targetNamespace = "http://server.jaxws.test.com/", className = "test.GetPersonList")
    @ResponseWrapper(localName = "getPersonListResponse", targetNamespace = "http://server.jaxws.test.com/", className = "test.GetPersonListResponse")
    @Action(input = "http://server.jaxws.test.com/Calculator/getPersonListRequest", output = "http://server.jaxws.test.com/Calculator/getPersonListResponse")
    public List<PersonBean> getPersonList();

}
